version: 0.1.{build}
branches:
  only:
    - master
  except:
    - gh-pages
configuration:
- Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore LocWarden.sln
image: Visual Studio 2017
build:
  verbosity: minimal
  project: LocWarden.sln
after_build:
- cmd: 7z a LocWarden.zip "%APPVEYOR_BUILD_FOLDER%\Publish\*"
artifacts:
- path: LocWarden.zip
  name: LocWarden.zip